# -----------  Agents  -----------
[[agents]]
id = "test_agent1"
name = "Agent 1"
public_address = "HcSCIUKodbWktcbmwyAaVrYnsbadi6b9sOV9D4ZoE8i333ZtcGw38Jn3U6u63qi"
keystore_file = "./agent1.keystore"

# -----------  DNA  -----------
[[dnas]]
id = "holochain_checkers"
file = "../generic-game-holochain/dist/generic-game.dna.json"
hash = "QmXTk8QLtYxw4bvPTuHupRZtXikueL1venGcLNhU6GXn2P"

[[instances]]
id = "holochain-checkers-instance"
dna = "holochain_checkers"
agent = "test_agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[interfaces]]
id = "checkers_websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 3301
[[interfaces.instances]]
id = "holochain-checkers-instance-interface"

[[interfaces]]
id = "checkers_http_interface"
[interfaces.driver]
type = "http"
port = 4401
[[interfaces.instances]]
id = "holochain-checkers-instance-interface"

# -----------  UI  -----------
[[ui_bundles]]
id = "main"
root_dir = "./ui-src"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3002
dna_interface = "holochain-checkers-instance-interface"

# -----------  Networking  -----------
# [network]
# n3h_mode = "REAL"
# n3h_persistence_path = "/tmp"
# n3h_log_level = "i"
# bootstrap_nodes = []
