# -----------  Agents  -----------
[[agents]]
id = "test_agent2"
name = "Agent 2"
public_address = "HcScj3nWSkA7BuacmvrI56rRBhd89CqfvvIVPnxBkmbpwbd6WQ6mK9c6M6rrh3z"
keystore_file = "./agent2.keystore"

# -----------  DNA  -----------
[[dnas]]
id = "holochain_checkers"
file = "../generic-game-holochain/dist/generic-game.dna.json"
hash = "QmXTk8QLtYxw4bvPTuHupRZtXikueL1venGcLNhU6GXn2P"

[[instances]]
id = "holochain-checkers-instance"
dna = "holochain_checkers"
agent = "test_agent2"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[interfaces]]
id = "checkers_websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 3301
[[interfaces.instances]]
id = "holochain-checkers-instance"

# -----------  UI  -----------
[[ui_bundles]]
id = "main"
root_dir = "./ui-agent2"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3002
dna_interface = "checkers_websocket_interface"

# -----------  Networking  -----------
[network]
# n3h_mode = "REAL"
n3h_persistence_path = "/tmp"
n3h_log_level = "i"
bootstrap_nodes = ["wss://192.168.1.101:41143/?a=HcSCjs7X7K8YiS8m7r857duSjJni48Spg83Z7yKg4GvbKwam8YNDv4bZHp9h8zi"]
